FROM node:alpine 

WORKDIR '/app'

COPY package.json . 
RUN npm install 

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
RUN mkdir /tmp/jest_rs && chmod -R 777 /tmp/jest_rs


COPY . . 

CMD ["npm", "run", "start"]
